print("         TOKO MAINAN ANAK")
print("     *************************")
nama_pembeli=input("Masukan nama pembeli = ")
kode_mainan = input("Masukan kode mainan = ")
harga       = int(input("Masukan harga = Rp "))
jumlah_beli = int(input("Masukan jumlah beli = "))
total_harga = (harga * jumlah_beli)
print("================================================")

print("Nama Pembeli =", str(nama_pembeli))
print("Kode Mainan =", str(kode_mainan))
print("Harga = Rp", str(harga))
print("Jumlah Beli =", str(jumlah_beli))
print("Total = Rp", str(total_harga))
